### ISSUE TITLE
Regression: Outcome of losing to dealer blackjack no longer shown

### ISSUE THREAD

**Issue by PhilHudson** [gdonald/blackjack-el#7]
After refusing insurance (I haven't tried accepting, I never do) the next hand is now dealt immediately. Previously, the loss was displayed and we prompted for the next action.

**Comment by gdonald** [comment]
I can't reproduce this yet.  Which deck-type are you using when it occurs?  Thanks.

**Comment by PhilHudson** [comment]
The regular one. (I don't yet understand when or why I might want to choose a different one.)

Problem persists after quitting Emacs, batch-byte-compiling blackjack.el, relaunching Emacs, `(require 'blackjack)` in IELM and `M-x blackjack`.

Further detail: money available reduces correctly.

**Comment by gdonald** [comment]
> The regular one. (I don't yet understand when or why I might want to choose a
> different one.)

The other deck-types are useful in development, for taking away randomness.  A deck of 8s makes the dealer bust.  A deck of As and Js produces a lot of blackjacks, and the insurance scenario.

> Problem persists after quitting Emacs, batch-byte-compiling blackjack.el, relaunching
> Emacs, `(require 'blackjack)` in IELM and `M-x blackjack`.

I'll try it this way.  I'm running it with `M-x eval-buffer` and then `M-x blackjack`.

**Comment by PhilHudson** [comment]
Note that the `blackjack-el` directory has to be in `load-path` (or pre-flighted via the EMACSLOADPATH environment variable, which is the approach I use).

**Comment by PhilHudson** [comment]
With my recent PR, we now get the outcome displayed and a "`Hand Action (?)`" prompt (instead of the expected "`Hand Action (h, s, d, ?)`"). However, no keys are accepted; the prompt simply re-displays as "`Hand Action (?)   [Please answer '?'.]`" Only `C-g` will get me out of it, after which I have to kill the blackjack buffer and `M-x blackjack` to continue.

**Comment by PhilHudson** [comment]
Got it, latest PR has the fix. I think we can close this now.
